### ISSUE TITLE
[Bug] Cannot choose which local port for the panel to use

### ISSUE THREAD

**Issue by SpaceGameDev568** [Moonlight-Panel/Installer#2]
When running through the CLI installer on my server, I found that I was unable to customize which port I want to have the Moonlight Panel use when communicating with the internet. Since port 80 and 443 on my server are already occupied, the installer fails with this stack trace:

```
Unhandled exception. System.Exception: docker: Error response from daemon: driver failed programming external connectivity on endpoint moonlight (5c86aa1a3e3738402bfca5ed5cd2369e9c497f0b2b8a3d72921788a17534d1d7): Error starting userland proxy: listen tcp4 0.0.0.0:80: bind: address already in use.

   at Installer.Helpers.BashHelper.ExecuteCommand(String command, Boolean ignoreErrors, Boolean showOutput)
   at Installer.Installers.PanelInstaller.<>c__DisplayClass0_0.<<Install>b__6>d.MoveNext()
--- End of stack trace from previous location ---
   at Installer.Helpers.DisplayHelper.<>c__DisplayClass0_0.<<RunAsStatus>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass16_0.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 79
--- End of stack trace from previous location ---
   at Spectre.Console.Status.<>c__DisplayClass17_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Status/Status.cs:line 120
--- End of stack trace from previous location ---
   at Spectre.Console.Progress.<>c__DisplayClass28_0`1.<<StartAsync>b__0>d.MoveNext() in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 133
--- End of stack trace from previous location ---
   at Spectre.Console.Internal.DefaultExclusivityMode.RunAsync[T](Func`1 func) in /_/src/Spectre.Console/Internal/DefaultExclusivityMode.cs:line 40
   at Spectre.Console.Progress.StartAsync[T](Func`2 action) in /_/src/Spectre.Console/Live/Progress/Progress.cs:line 116
   at Spectre.Console.Status.StartAsync[T](String status, Func`2 func) in /_/src/Spectre.Console/Live/Status/Status.cs:line 117
   at Spectre.Console.Status.StartAsync(String status, Func`2 action) in /_/src/Spectre.Console/Live/Status/Status.cs:line 77
   at Installer.Helpers.DisplayHelper.RunAsStatus(String statusText, Func`1 work)
   at Installer.Installers.PanelInstaller.Install()
   at Program.<Main>$(String[] args)
   at Program.<Main>(String[] args)
install.sh: line 6: 213804 Aborted                 sudo ./Installer
```

It would be better if the user could input which local port they want to use for HTTP/HTTPS during the configuration phase, before running the docker container.

**Comment by Masu-Baumgartner** [comment]
Closed as v2 has implemented this option
